version: '2'

#docker run -d -p 8080:8080 -p 8009:8009 -v /home/dockers/alfred/webapps:/opt/tomcat/webapps dordoka/rpi-tomcat
#dordoka/tomcat:xenial

services:
# Defino contenedor de BD
   alfred_tomcat:
     image: matiuh/alfred-tomcat
     container_name: alfred_tomcat
     #restart: always
     ports:
       - 80:8080
       - 81:8009
     volumes:
       - ./webapps:/opt/tomcat/webapps
     privileged: true
     depends_on:
       - alfred_db

# Defino base de datos
   alfred_db:
     image: hypriot/rpi-mysql
     container_name: alfred_db
     volumes:
       - "./db:/var/lib/mysql"
     #restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: alfred
       MYSQL_USER: alfred
       MYSQL_PASSWORD: 114529

# Defino contenedor de phpmyadmin
   phpmyadmin-desa:
     image: wednus/rpi-phpmyadmin
     container_name: alfred_phpmyadmin
     environment:
       - PMA_HOST=alfred_db
     #restart: always
     ports:
       - 82:80
     volumes:
       - /sessions
     #mem_limit: 128m
